add chat
kuplevich-max/Chat pull request #1
Opened 2021-03-27 13:20 UTC by kuplevich-max

2021-03-28 12:33 UTC, gmltA requested changes
I don't see you sending message history to the reconnected user.

2021-03-29 08:51 UTC, kuplevich-max commented
When the user reconnects, he must send a message, and then the whole history will be restored

2021-03-29 17:40 UTC, gmltA commented
> When the user reconnects, he must send a message, and then the whole history will be restored

I got that. Cuz it was written in the file. But I explicitly asked to re-send it upon reconnection.

2021-05-18 19:39 UTC, gmltA approved these changes

2021-05-19 19:49 UTC, merged